### ISSUE TITLE
Practica 8 - Roadmap

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-promastergamer777#1]

**Comment by FedericoVictorianoSierra** [comment]
[Práctica 8 Estuctura Desglose Trabajo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-promastergamer777/files/13272179/Practica.8.Estuctura.Desglose.Trabajo.pdf)

**Comment by Heidi-19** [comment]
[Práctica 8 Estuctura Desglose Trabajo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-promastergamer777/files/13272192/Practica.8.Estuctura.Desglose.Trabajo.pdf)

**Comment by JoseABCruz** [comment]
[Práctica 8 Estuctura Desglose Trabajo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-promastergamer777/files/13272205/Practica.8.Estuctura.Desglose.Trabajo.pdf)

**Comment by Aricel117** [comment]
Calificación: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
